<?xml version="1.0" encoding="utf-8"?><Database Name="PortalCliente" EntityNamespace="PortalCliente.Models" ContextNamespace="PortalCliente.Models" Class="PortalClienteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PortalCliente.mssql.somee.com;Initial Catalog=PortalCliente;User ID=portalcliente_sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PortalClienteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CONFIG_Parameter" Member="CONFIG_Parameters">
    <Type Name="CONFIG_Parameter">
      <Column Name="parameter_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="parameter_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="dataType_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CAT_DataType" Member="CAT_DataTypes">
    <Type Name="CAT_DataType">
      <Column Name="dataType_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dataType_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SEG_User" Member="SEG_Users">
    <Type Name="SEG_User">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="profile_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OP_CustomerMessage" Member="OP_CustomerMessages">
    <Type Name="OP_CustomerMessage">
      <Column Name="customerMessage_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customerEmail" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="customerName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="customerLastName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="customerPhone01" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="customerPhone2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[read]" Member="read" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="userRead" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="readDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CAT_Profile" Member="CAT_Profiles">
    <Type Name="CAT_Profile">
      <Column Name="profile_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="profile_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>